[build]
  publish = "_site"
  command = "npm run build-production"

[[plugins]]
package = "./plugins/keep-data-cache"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
# No redirects needed since it is my own instance
# [[redirects]]
  # from = "https://speedlichew.netlify.app"
  # to = "https://www.speedlify.dev"
  # status = 301
  # force = true
